spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications_database
  application:
    name: notification-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka