server:
  port: 9000
spring:
  application:
    name: registry-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://127.0.0.1:9000/eureka